### ISSUE TITLE
cockpit needs to be build here

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/dockers#12]
see
https://github.com/Jumpscale/jscockpit/blob/master/scripts/building.py

- make sure we checkout the jscockpit repo & then build

**Comment by zaibon** [comment]
We should not use the build script form jscockpit repo. Instead extract the cuisine recipe of the build and put in the the build.py file. This build.py is the recipe of how to build the cockpit.

**Comment by zaibon** [comment]
https://github.com/Jumpscale/dockers/pull/25/commits/9648b8276abbe026a02acd5869135dc8415f3a4c
