### ISSUE TITLE
91_ubuntu1604_g8os_test

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/dockers#24]
This docker is responsible to test if the sandbox and the fuse filesystem works.

Start from our alpine docker image.
Install https://github.com/g8os/fs and try to start jumpscale.

**Comment by despiegk** [comment]
better to start from ubuntu 1604 for now, there is an issue with alpine doesn;t do glibc at this point, would need to fix that first
it would be nice though

**Comment by despiegk** [comment]
see the directory 91_ubuntu1604_g8os_test for more details what to do
